import 'dart:typed_data';

import 'package:measurement/measurement.dart';
import 'package:test/test.dart';

void main() {
  group('PPM (P6)', () {
    test('round-trips an image exactly', () {
      final image = RgbImage.filled(4, 3, 10, 20, 30);
      image.setPixel(2, 1, 200, 100, 50);
      final decoded = Ppm.decode(Ppm.encode(image));

      expect(decoded.width, 4);
      expect(decoded.height, 3);
      expect(decoded.bytes, image.bytes);
      expect(decoded.red(2, 1), 200);
      expect(decoded.green(2, 1), 100);
      expect(decoded.blue(2, 1), 50);
    });

    test('skips comments in the header', () {
      final body = <int>[
        ...'P6\n# generated by a fixture tool\n2 1\n255\n'.codeUnits,
        1,
        2,
        3,
        4,
        5,
        6,
      ];
      final decoded = Ppm.decode(Uint8List.fromList(body));
      expect(decoded.width, 2);
      expect(decoded.red(0, 0), 1);
      expect(decoded.blue(1, 0), 6);
    });

    test('rejects a non-P6 magic number', () {
      expect(
        () => Ppm.decode(Uint8List.fromList('P3\n1 1\n255\n'.codeUnits)),
        throwsA(isA<FormatException>()),
      );
    });

    test('rejects a truncated raster instead of padding it', () {
      final body = <int>[...'P6\n2 1\n255\n'.codeUnits, 1, 2, 3];
      expect(
        () => Ppm.decode(Uint8List.fromList(body)),
        throwsA(isA<FormatException>()),
      );
    });

    test('rejects a bit depth it cannot represent', () {
      expect(
        () => Ppm.decode(Uint8List.fromList('P6\n1 1\n65535\n'.codeUnits)),
        throwsA(isA<FormatException>()),
      );
    });
  });

  group('RgbImage', () {
    test('bilinear sampling reproduces pixel centres exactly', () {
      final image = RgbImage.filled(3, 3, 0, 0, 0);
      image.setPixel(1, 1, 255, 128, 64);
      final s = image.sampleBilinear(1.0, 1.0)!;
      expect(s.r, closeTo(1.0, 1e-12));
      expect(s.g, closeTo(128 / 255, 1e-12));
      expect(s.b, closeTo(64 / 255, 1e-12));
    });

    test('bilinear sampling interpolates between neighbours', () {
      final image = RgbImage.filled(2, 1, 0, 0, 0);
      image.setPixel(0, 0, 0, 0, 0);
      image.setPixel(1, 0, 200, 200, 200);
      final s = image.sampleBilinear(0.5, 0.0)!;
      expect(s.r, closeTo(100 / 255, 1e-12));
    });

    test('returns null outside the frame rather than clamping to the edge', () {
      // Clamping would fabricate a value: a sample that fell off the frame is
      // missing information, and substituting the nearest edge pixel hides
      // exactly the misalignment the geometry stage exists to catch.
      final image = RgbImage.filled(2, 2, 10, 10, 10);
      expect(image.sampleBilinear(-0.01, 0.0), isNull);
      expect(image.sampleBilinear(0.0, -0.01), isNull);
      expect(image.sampleBilinear(1.01, 0.0), isNull);
      expect(image.sampleBilinear(0.0, 1.01), isNull);
      expect(image.sampleBilinear(1.0, 1.0), isNotNull);
    });

    test('rejects a buffer of the wrong size', () {
      expect(() => RgbImage(2, 2, Uint8List(10)), throwsArgumentError);
    });
  });
}
